"""add deigner

Revision ID: 064e6dfc333f
Revises: 15585424ea9e
Create Date: 2024-06-01 11:13:50.903157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064e6dfc333f'
down_revision = '15585424ea9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['designer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_designer_id'), ['designer_id'], unique=False)

    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.drop_index('ix_fold_designer_id')
        batch_op.drop_index('ix_fold_timestamp')
        batch_op.drop_index('ix_fold_user_id')

    op.drop_table('fold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fold',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('design', sa.VARCHAR(length=140), nullable=False),
    sa.Column('paper_type', sa.VARCHAR(length=140), nullable=False),
    sa.Column('paper_size', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=140), nullable=False),
    sa.Column('designer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['designer.id'], name='designer_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.create_index('ix_fold_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_fold_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_fold_designer_id', ['designer_id'], unique=False)

    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_designer_id'))

    op.drop_table('design')
    # ### end Alembic commands ###
