"""empty message

Revision ID: 15585424ea9e
Revises: 794856f51104
Create Date: 2024-04-11 07:22:00.601620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15585424ea9e'
down_revision = '794856f51104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_fold_designer_id'), ['designer_id'], unique=False)
        batch_op.create_foreign_key("designer_id", 'designer', ['designer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fold_designer_id'))
        batch_op.drop_column('designer_id')

    # ### end Alembic commands ###
