"""add notes to fold

Revision ID: 36fa6d6329b6
Revises: 3a300e7c06c3
Create Date: 2024-04-10 17:31:26.649762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fa6d6329b6'
down_revision = '3a300e7c06c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
