"""folds table

Revision ID: 3a300e7c06c3
Revises: ce0e1bcfcb68
Create Date: 2024-04-10 17:24:20.787383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a300e7c06c3'
down_revision = 'ce0e1bcfcb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designer', sa.String(length=140), nullable=False),
    sa.Column('design', sa.String(length=140), nullable=False),
    sa.Column('paper_type', sa.String(length=140), nullable=False),
    sa.Column('paper_size', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fold_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_fold_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fold_user_id'))
        batch_op.drop_index(batch_op.f('ix_fold_timestamp'))

    op.drop_table('fold')
    # ### end Alembic commands ###
