"""empty message

Revision ID: 794856f51104
Revises: 36fa6d6329b6
Create Date: 2024-04-11 07:20:38.295809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794856f51104'
down_revision = '36fa6d6329b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.drop_column('designer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designer', sa.VARCHAR(length=140), nullable=False))

    # ### end Alembic commands ###
